# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 558578ae9f9b089dd1b1dc45e587dcda8f09ca682e649e6d3b7b21fd3dc9c9bd3d4bea914e4834f8f78d894358f4f8829de0ff66d1776a30c60d3a0cd2ff7b04

test:
  secret_key_base: c4d44bcbc0d719f3badd9c161a2c530178cf866276572a0d5f5d8213da8a76ce492ea0c2619194213552b7fac2b0664afd7812974f9b853500060ef4011b55a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
